title: Sam Fritz-Schreck # your name (or website title) here
logo: images/DA Photo.jpg?raw=True # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student <br>
  <a href="https://nps.edu/web/or/operations-analysis-360">M.S. Operations Research</a> <br>
  (Projected June 2024) <br>
  Naval Postgraduate School
  
theme: jekyll-theme-minimal
google_analytics: G-FB6ZCZ0R71
