title: Sam Fritz-Schreck # your name (or website title) here
logo: images/DA Photo.jpg?raw=TRUE # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student <br>
  <a href="https://nps.edu/web/or/operations-analysis-360">M.S. Operations Research</a> <br>
  (Projected June 2024) <br>
  Naval Postgraduate School
  <br><br>
  Thesis Advisor: <br>
  <a href="http://faculty.nps.edu/ryoshida/">Ruriko Yoshida</a> <br>
  Second Reader: <br>
  <br><br>
  {%- assign date_format = site.minima.date_format | default: '%b %-d, %Y' -%}
  {%- if page.last_modified_at -%}
      Last updated: {%- page.last_modified_at | date: date_format -%}
  {%- else -%}
      Last updated: {%- page.date | date: date_format -%}
  {%- endif -%}
  
theme: jekyll-theme-minimal
google_analytics: G-FB6ZCZ0R71
