title: Sam Fritz-Schreck # your name (or website title) here
logo: images/DA Photo.jpg?raw=TRUE # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student <br>
  <a href="https://nps.edu/web/or/operations-analysis-360">M.S. Operations Research</a> <br>
  (Projected June 2024) <br>
  Naval Postgraduate School
  <br><br>
  Thesis Advisor: <br>
  <a href="http://faculty.nps.edu/ryoshida/">Ruriko Yoshida</a> <br>
  <br><br>
  Second Reader: <br>
  <br><br>
  Last updated: <span id="git-last-commit-date">$git_last_commit_date</span>
  
theme: jekyll-theme-minimal
google_analytics: G-FB6ZCZ0R71
